[phases.setup]
nixPkgs = ["php", "phpExtensions.fileinfo", "phpExtensions.sqlite3", "phpExtensions.pdo", "phpExtensions.pdo_sqlite"]

[phases.build]
cmds = ["mkdir -p uploads && chmod 777 uploads"]

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"
