[phases.setup]
nixPkgs = ["php82", "php82Extensions.fileinfo", "php82Extensions.sqlite3"]

[phases.build]
cmds = ["mkdir -p uploads && chmod 777 uploads"]

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"
